//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dulceria.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        public int idtarjeta { get; set; }
        public int Nro__de_tarjeta { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public int CVV { get; set; }
        public int idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
